services:
  # Flask RSVP application
  - type: web
    name: rsvp-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: MAIL_SERVER
        value: albea.websitewelcome.com
      - key: MAIL_PORT
        value: 465
      - key: MAIL_USERNAME
        value: rsvp@boda.com.py
      - key: MAIL_PASSWORD
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: SUPER_ADMIN_USER
        value: admin
      - key: SUPER_ADMIN_PASS
        sync: false
    buildFilter:
      paths:
        - app/**
        - requirements.txt
        - app.py
    database:
      - name: rsvp-db
        plan: free
    preDeployCommand: python render_migrate.py
